name: Azsubscanner
on:
   push:
     branches: [main]
jobs:
  build: 
    name: Run script
    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v1
    - name: script


      run: C:\subscriptionscanner.ps1 
   
